name: Verify packages

on:
  push:
    branches:
      - trunk

jobs:
  reproduce:
    name: "Reproduce ${{ matrix.tag }} / ${{ matrix.source }}"
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - github-wordpress-wordpress-develop
          - develop.svn.wordpress.org
          - core.trac.wordpress.org
      fail-fast: false
    uses: johnbillion/rave/.github/workflows/reproduce.yml@trunk
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  verify:
    name: "Verify ${{ matrix.tag }} ${{ matrix.package }} / ${{ matrix.source }}"
    needs:
      - reproduce
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - github-wordpress-wordpress-develop
          - develop.svn.wordpress.org
          - core.trac.wordpress.org
        package:
          - github-wordpress-wordpress-zip
          - github-wordpress-wordpress-tar
          - wordpress.org-zip
          - wordpress.org-tar
          - downloads.wordpress.org-zip
          - downloads.wordpress.org-tar
          - build.trac.wordpress.org

      fail-fast: false
    uses: johnbillion/rave/.github/workflows/verify.yml@trunk
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
      package: ${{ matrix.package }}
