name: Compare releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for WordPress release'
        required: true

jobs:
  source:
    name: Build source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}
          repository: WordPress/wordpress-develop

      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version

      - name: Install npm Dependencies
        run: npm ci

      - name: Run Emoji precommit task
        run: npm run grunt precommit:emoji
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build WordPress
        run: npm run build

      - name: Convert some line endings to CRLF
        run: |
          sed -i 's/$/\r/' build/license.txt
          sed -i 's/$/\r/' build/wp-includes/images/crystal/license.txt

      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: wordpress-build
          path: build
          if-no-files-found: error

  compare:
    name: Compare / ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - github-wordpress
          - wordpress-org-zip
          - wordpress-org-tar
    needs:
      - source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wordpress-build
          path: source

      - name: Get zip file from GitHub
        if: matrix.distro == 'github-wordpress'
        run: |
          wget -O github-wordpress.zip https://github.com/WordPress/WordPress/archive/refs/tags/${{ github.event.inputs.tag_name }}.zip
          unzip github-wordpress.zip -d wordpress
          mv wordpress/WordPress-${{ github.event.inputs.tag_name }} distro

      - name: Get zip file from wordpress.org
        if: matrix.distro == 'wordpress-org-zip'
        run: |
          wget -O wordpress-org.zip https://wordpress.org/wordpress-${{ github.event.inputs.tag_name }}.zip
          unzip wordpress-org.zip -d wordpress
          mv wordpress/wordpress distro

      - name: Get tar file from wordpress.org
        if: matrix.distro == 'wordpress-org-tar'
        run: |
          wget -O wordpress-org.tar.gz https://wordpress.org/wordpress-6.6.2.tar.gz
          mkdir wordpress
          tar -xzf wordpress-org.tar.gz -C wordpress
          mv wordpress/wordpress distro

      - name: Compare files
        run: |
          docker compose run diffoscope
