name: Compare releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for WordPress release'
        required: true

jobs:
  github-wordpress:
    name: GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Download build from GitHub
        run: |
          wget -O github-wordpress.zip https://github.com/WordPress/WordPress/archive/refs/tags/${{ github.event.inputs.tag_name }}.zip
      - name: Upload GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-wordpress
          path: github-wordpress.zip

  wordpress-org:
    name: WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Download distribution file from wordpress.org
        run: |
          wget -O wordpress-org.zip https://wordpress.org/wordpress-${{ github.event.inputs.tag_name }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-org
          path: wordpress-org.zip

  compare_files:
    name: Compare
    runs-on: ubuntu-latest
    needs:
      - wordpress-org
      - github-wordpress
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Debug artifacts
        run: |
          ls -l
          ls -l github-wordpress
          ls -l wordpress-org
      - name: Extract everything
        run: |
          unzip github-wordpress/github-wordpress.zip -d github-wordpress-files
          mv github-wordpress-files/WordPress-${{ github.event.inputs.tag_name }} distro
          unzip wordpress-org/wordpress-org.zip -d wordpress-org-files
          mv wordpress-org-files/wordpress source
      - name: Compare files
        run: |
          docker compose run diffoscope
