name: Verify packages

on:
  push:
    branches:
      - trunk

jobs:
  reproduce:
    name: "Reproduce ${{ matrix.tag }}"
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - github-wordpress-develop
          - develop.svn.w.org
          - core.trac.w.org
      fail-fast: false
    uses: johnbillion/rave/.github/workflows/reproduce.yml@trunk
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  verify:
    name: "Verify ${{ matrix.tag }} ${{ matrix.package }}"
    needs:
      - reproduce
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - github-wordpress-develop
          - develop.svn.w.org
          - core.trac.w.org
        package:
          - github-zip
          - github-tar
          - w.org-zip
          - w.org-tar
          - downloads.w.org-zip
          - downloads.w.org-tar
          - build.trac.w.org

      fail-fast: false
    uses: johnbillion/rave/.github/workflows/verify.yml@trunk
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
      package: ${{ matrix.package }}
