name: Compare WordPress Releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for WordPress release'
        required: true

jobs:
  download_wordpress_github:
    runs-on: ubuntu-latest
    steps:
      - name: Download build from GitHub
        run: |
          wget -O wordpress-github.zip https://github.com/WordPress/WordPress/archive/refs/tags/${{ github.event.inputs.tag_name }}.zip
      - name: Upload GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-github
          path: wordpress-github.zip

  download_wordpress_org:
    runs-on: ubuntu-latest
    steps:
      - name: Download distribution file from wordpress.org
        run: |
          wget -O wordpress-org.zip https://wordpress.org/wordpress-${{ github.event.inputs.tag_name }}.zip
      - name: Upload WordPress.org artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-org
          path: wordpress-org.zip

  compare_files:
    runs-on: ubuntu-latest
    needs:
      - download_wordpress_org
      - download_wordpress_github
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Debug artifacts
        run: |
          ls -l
      - name: Extract everything
        run: |
          unzip wordpress-github.zip -d wordpress-github
          unzip wordpress-org.zip -d wordpress-org
      - name: Install diffoscope
        run: sudo apt-get update && sudo apt-get install -y diffoscope
      - name: Compare files
        run: |
          diffoscope wordpress-github/WordPress-${{ github.event.inputs.tag_name }} wordpress-org/wordpress
